package test.geeekr.db;

import java.util.Date;

import com.geeekr.db.Model;

/**
 * Posts generated by hbm2java
 */
public class Post extends Model implements java.io.Serializable {

    private static final long serialVersionUID = 4375802806687115318L;

    private Long id;
    private String title;
    private String slug;
    private String markdown;
    private String html;
    private String image;
    private boolean featured;
    private boolean page;
    private String status;
    private int authorId;
    private Date createdAt;
    private int createdBy;
    private Date updatedAt;
    private Integer updatedBy;
    private Date publishedAt;
    private Integer publishedBy;

    public Post() {
    }

    public Post(String title, String slug, boolean featured, boolean page, String status, int authorId, Date createdAt, int createdBy) {
        this.title = title;
        this.slug = slug;
        this.featured = featured;
        this.page = page;
        this.status = status;
        this.authorId = authorId;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }

    public Post(String title, String slug, String markdown, String html, String image, boolean featured, boolean page, String status, int authorId,
            Date createdAt, int createdBy, Date updatedAt, Integer updatedBy, Date publishedAt, Integer publishedBy) {
        this.title = title;
        this.slug = slug;
        this.markdown = markdown;
        this.html = html;
        this.image = image;
        this.featured = featured;
        this.page = page;
        this.status = status;
        this.authorId = authorId;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.publishedAt = publishedAt;
        this.publishedBy = publishedBy;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSlug() {
        return this.slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getMarkdown() {
        return this.markdown;
    }

    public void setMarkdown(String markdown) {
        this.markdown = markdown;
    }

    public String getHtml() {
        return this.html;
    }

    public void setHtml(String html) {
        this.html = html;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public boolean isFeatured() {
        return this.featured;
    }

    public void setFeatured(boolean featured) {
        this.featured = featured;
    }

    public boolean isPage() {
        return this.page;
    }

    public void setPage(boolean page) {
        this.page = page;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getAuthorId() {
        return this.authorId;
    }

    public void setAuthorId(int authorId) {
        this.authorId = authorId;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getPublishedAt() {
        return this.publishedAt;
    }

    public void setPublishedAt(Date publishedAt) {
        this.publishedAt = publishedAt;
    }

    public Integer getPublishedBy() {
        return this.publishedBy;
    }

    public void setPublishedBy(Integer publishedBy) {
        this.publishedBy = publishedBy;
    }

    @Override
    public String toString() {
        return "Posts [id=" + id + ", title=" + title + ", slug=" + slug + ", markdown=" + markdown + ", html=" + html + ", image=" + image
                + ", featured=" + featured + ", page=" + page + ", status=" + status + ", authorId=" + authorId + ", createdAt=" + createdAt
                + ", createdBy=" + createdBy + ", updatedAt=" + updatedAt + ", updatedBy=" + updatedBy + ", publishedAt=" + publishedAt
                + ", publishedBy=" + publishedBy + "]";
    }

}
